name: Pull Request Notification

on:
  pull_request:
    branches:
      - UAT
    types: [opened, synchronize]

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.engineerhasnain88@gmail.com }}
        password: ${{ secrets.97575400 }}
        subject: 'Pull Request from Develop to UAT'
        body: |
          A new pull request has been created from the develop branch to the UAT branch.
          Please review the pull request at ${{ github.event.pull_request.html_url }}
        to: hasnain.wali@csd.gov.pk
        from: engineerhasnain88@gmail.com
